options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 port 53 { any; };
    allow-query { any; };
    allow-transfer { any; };
    recursion no;
};

zone "zonetransfer.test" {
    type master;
    file "/etc/bind/db.zonetransfer.test";
    allow-transfer { any; };
};
